CREATE TABLE "public"."instruments" (
  "instrument_id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "listing_id"                bigint NOT NULL,
  "ticker"                    text   NOT NULL,
  "series"                    text,
  "predecessor_instrument_id" bigint,
  "effective_from"            date   NOT NULL,
  "effective_to"              date,
  CONSTRAINT "instruments_listing_id_ticker_effective_from_key" UNIQUE (listing_id, ticker, effective_from),
  CONSTRAINT "instruments_pkey" PRIMARY KEY (instrument_id),
  CONSTRAINT "instruments_predecessor_instrument_id_fkey" FOREIGN KEY (predecessor_instrument_id) REFERENCES public.instruments(instrument_id),
  CONSTRAINT "instruments_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES public.listings(listing_id)
);

ALTER TABLE "public"."instruments"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_instruments_ticker ON public.instruments USING btree (ticker);

CREATE POLICY "Public read instruments" ON "public"."instruments"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."instruments" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."instruments" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."instruments" TO "service_role";
