CREATE TABLE "public"."issuer_name_history" (
  "id"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "issuer_id"       bigint NOT NULL,
  "former_name"     text   NOT NULL,
  "effective_from"  date   NOT NULL,
  "effective_to"    date,
  "source_document" text,
  CONSTRAINT "issuer_name_history_pkey" PRIMARY KEY (id),
  CONSTRAINT "issuer_name_history_issuer_id_fkey" FOREIGN KEY (issuer_id) REFERENCES public.issuers(issuer_id)
);

ALTER TABLE "public"."issuer_name_history"
  ENABLE ROW LEVEL SECURITY;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."issuer_name_history" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."issuer_name_history" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."issuer_name_history" TO "service_role";
