CREATE TABLE "public"."issuers" (
  "issuer_id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "legal_name"         text                     NOT NULL,
  "short_name"         text,
  "incorporation_date" date,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"         timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "issuers_pkey" PRIMARY KEY (issuer_id)
);

ALTER TABLE "public"."issuers"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read issuers" ON "public"."issuers"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."issuers" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."issuers" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."issuers" TO "service_role";
