CREATE TABLE "public"."listings" (
  "listing_id"     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "security_id"    bigint NOT NULL,
  "exchange"       text   NOT NULL,
  "listing_date"   date,
  "delisting_date" date,
  CONSTRAINT "listings_pkey" PRIMARY KEY (listing_id),
  CONSTRAINT "listings_security_id_exchange_key" UNIQUE (security_id, exchange),
  CONSTRAINT "listings_security_id_fkey" FOREIGN KEY (security_id) REFERENCES public.securities(security_id)
);

ALTER TABLE "public"."listings"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read listings" ON "public"."listings"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."listings" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."listings" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."listings" TO "service_role";
