CREATE TABLE "public"."prices" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "instrument_id" bigint                   NOT NULL,
  "trade_date"    date                     NOT NULL,
  "open"          numeric,
  "high"          numeric,
  "low"           numeric,
  "close"         numeric,
  "adj_close"     numeric,
  "volume"        bigint,
  "turnover"      numeric,
  "delivery_pct"  numeric,
  "source"        text                     NOT NULL,
  "ingested_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "prices_instrument_id_fkey" FOREIGN KEY (instrument_id) REFERENCES public.instruments(instrument_id),
  CONSTRAINT "prices_instrument_id_trade_date_source_key" UNIQUE (instrument_id, trade_date, source),
  CONSTRAINT "prices_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."prices"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_prices_instrument_date ON public.prices USING btree (instrument_id, trade_date);

CREATE POLICY "Public read prices" ON "public"."prices"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."prices" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."prices" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."prices" TO "service_role";
