CREATE TABLE "public"."securities" (
  "security_id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "issuer_id"               bigint                   NOT NULL,
  "isin"                    text,
  "security_type"           text                     NOT NULL,
  "status"                  text                     NOT NULL DEFAULT 'active'::text,
  "predecessor_security_id" bigint,
  "successor_security_id"   bigint,
  "listing_date"            date,
  "delisting_date"          date,
  "created_at"              timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "securities_isin_key" UNIQUE (isin),
  CONSTRAINT "securities_issuer_id_fkey" FOREIGN KEY (issuer_id) REFERENCES public.issuers(issuer_id),
  CONSTRAINT "securities_pkey" PRIMARY KEY (security_id),
  CONSTRAINT "securities_predecessor_security_id_fkey" FOREIGN KEY (predecessor_security_id) REFERENCES public.securities(security_id),
  CONSTRAINT "securities_successor_security_id_fkey" FOREIGN KEY (successor_security_id) REFERENCES public.securities(security_id)
);

ALTER TABLE "public"."securities"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_securities_issuer ON public.securities USING btree (issuer_id);

CREATE POLICY "Public read securities" ON "public"."securities"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."securities" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."securities" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."securities" TO "service_role";
