


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."instruments" (
    "instrument_id" bigint NOT NULL,
    "listing_id" bigint NOT NULL,
    "ticker" "text" NOT NULL,
    "series" "text",
    "predecessor_instrument_id" bigint,
    "effective_from" "date" NOT NULL,
    "effective_to" "date"
);


ALTER TABLE "public"."instruments" OWNER TO "postgres";


ALTER TABLE "public"."instruments" ALTER COLUMN "instrument_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."instruments_instrument_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."issuer_name_history" (
    "id" bigint NOT NULL,
    "issuer_id" bigint NOT NULL,
    "former_name" "text" NOT NULL,
    "effective_from" "date" NOT NULL,
    "effective_to" "date",
    "source_document" "text"
);


ALTER TABLE "public"."issuer_name_history" OWNER TO "postgres";


ALTER TABLE "public"."issuer_name_history" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."issuer_name_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."issuers" (
    "issuer_id" bigint NOT NULL,
    "legal_name" "text" NOT NULL,
    "short_name" "text",
    "incorporation_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."issuers" OWNER TO "postgres";


ALTER TABLE "public"."issuers" ALTER COLUMN "issuer_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."issuers_issuer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listings" (
    "listing_id" bigint NOT NULL,
    "security_id" bigint NOT NULL,
    "exchange" "text" NOT NULL,
    "listing_date" "date",
    "delisting_date" "date"
);


ALTER TABLE "public"."listings" OWNER TO "postgres";


ALTER TABLE "public"."listings" ALTER COLUMN "listing_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listings_listing_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."prices" (
    "id" bigint NOT NULL,
    "instrument_id" bigint NOT NULL,
    "trade_date" "date" NOT NULL,
    "open" numeric,
    "high" numeric,
    "low" numeric,
    "close" numeric,
    "adj_close" numeric,
    "volume" bigint,
    "turnover" numeric,
    "delivery_pct" numeric,
    "source" "text" NOT NULL,
    "ingested_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."prices" OWNER TO "postgres";


ALTER TABLE "public"."prices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."prices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."securities" (
    "security_id" bigint NOT NULL,
    "issuer_id" bigint NOT NULL,
    "isin" "text",
    "security_type" "text" NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    "predecessor_security_id" bigint,
    "successor_security_id" bigint,
    "listing_date" "date",
    "delisting_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."securities" OWNER TO "postgres";


ALTER TABLE "public"."securities" ALTER COLUMN "security_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."securities_security_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."instruments"
    ADD CONSTRAINT "instruments_listing_id_ticker_effective_from_key" UNIQUE ("listing_id", "ticker", "effective_from");



ALTER TABLE ONLY "public"."instruments"
    ADD CONSTRAINT "instruments_pkey" PRIMARY KEY ("instrument_id");



ALTER TABLE ONLY "public"."issuer_name_history"
    ADD CONSTRAINT "issuer_name_history_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."issuers"
    ADD CONSTRAINT "issuers_pkey" PRIMARY KEY ("issuer_id");



ALTER TABLE ONLY "public"."listings"
    ADD CONSTRAINT "listings_pkey" PRIMARY KEY ("listing_id");



ALTER TABLE ONLY "public"."listings"
    ADD CONSTRAINT "listings_security_id_exchange_key" UNIQUE ("security_id", "exchange");



ALTER TABLE ONLY "public"."prices"
    ADD CONSTRAINT "prices_instrument_id_trade_date_source_key" UNIQUE ("instrument_id", "trade_date", "source");



ALTER TABLE ONLY "public"."prices"
    ADD CONSTRAINT "prices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."securities"
    ADD CONSTRAINT "securities_isin_key" UNIQUE ("isin");



ALTER TABLE ONLY "public"."securities"
    ADD CONSTRAINT "securities_pkey" PRIMARY KEY ("security_id");



CREATE INDEX "idx_instruments_ticker" ON "public"."instruments" USING "btree" ("ticker");



CREATE INDEX "idx_prices_instrument_date" ON "public"."prices" USING "btree" ("instrument_id", "trade_date");



CREATE INDEX "idx_securities_issuer" ON "public"."securities" USING "btree" ("issuer_id");



ALTER TABLE ONLY "public"."instruments"
    ADD CONSTRAINT "instruments_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("listing_id");



ALTER TABLE ONLY "public"."instruments"
    ADD CONSTRAINT "instruments_predecessor_instrument_id_fkey" FOREIGN KEY ("predecessor_instrument_id") REFERENCES "public"."instruments"("instrument_id");



ALTER TABLE ONLY "public"."issuer_name_history"
    ADD CONSTRAINT "issuer_name_history_issuer_id_fkey" FOREIGN KEY ("issuer_id") REFERENCES "public"."issuers"("issuer_id");



ALTER TABLE ONLY "public"."listings"
    ADD CONSTRAINT "listings_security_id_fkey" FOREIGN KEY ("security_id") REFERENCES "public"."securities"("security_id");



ALTER TABLE ONLY "public"."prices"
    ADD CONSTRAINT "prices_instrument_id_fkey" FOREIGN KEY ("instrument_id") REFERENCES "public"."instruments"("instrument_id");



ALTER TABLE ONLY "public"."securities"
    ADD CONSTRAINT "securities_issuer_id_fkey" FOREIGN KEY ("issuer_id") REFERENCES "public"."issuers"("issuer_id");



ALTER TABLE ONLY "public"."securities"
    ADD CONSTRAINT "securities_predecessor_security_id_fkey" FOREIGN KEY ("predecessor_security_id") REFERENCES "public"."securities"("security_id");



ALTER TABLE ONLY "public"."securities"
    ADD CONSTRAINT "securities_successor_security_id_fkey" FOREIGN KEY ("successor_security_id") REFERENCES "public"."securities"("security_id");



ALTER TABLE "public"."instruments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."issuer_name_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."issuers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."prices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."securities" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."instruments" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."instruments" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."instruments" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuer_name_history" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuer_name_history" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuer_name_history" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuers" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuers" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."issuers" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."listings" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."listings" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."listings" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."prices" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."prices" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."prices" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."securities" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."securities" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."securities" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";







